version: "3.8"

services:
  app:
    build: .
    working_dir: /app
    command: rdebug-ide --host 0.0.0.0 --port 1234 --skip_wait_for_start --disable-int-handler -- app.rb
    ports:
      - 4567:4567
    volumes:
      - ./:/app
      - bundle:/app/vendor/bundle

volumes:
  bundle:
