version: "3.8"

services:
  app:
    image: node:14.16-buster
    working_dir: /app
    command: node index.js --inspect
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
